Add stack, queue, linkedlist in files
tsarkar9/STACK-QUEUE-LINKED-LIST pull request #2
Opened 2021-09-03 15:39 UTC by 0xInfection

The pull request properly adds 3 files in python. Corrects #1.

2021-09-03 16:07 UTC, chiranjiv11 approved these changes

2021-09-03 16:08 UTC, chiranjiv11 approved these changes

2021-09-04 00:28 UTC, noraman003 approved these changes

2021-09-04 10:00 UTC, whitefight18 requested changes
In the Code of the file - queue.py , at line 22, there's a spelling mistake - "Queue is Emoty" , that should be "Queue is Empty" ; similar mistake in the code of the file - stack.py ; similar changes to the spelling of "Emoty" is required …

2021-09-04 10:41 UTC, merged